apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
spec:
  selector:
    matchLabels:
      service: mongo-db
  replicas: 1
  serviceName: mongo-db
  template:
    metadata:
      labels:
        service: mongo-db
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: node-role.kubernetes.io/worker
                  operator: In
                  values:
                    - worker
                - key: type
                  operator: In
                  values:
                    - on-premise
                - key: provider
                  operator: In
                  values:
                    - host
                - key: service
                  operator: In
                  values:
                    - virtualbox
                - key: region
                  operator: In
                  values:
                    - local
                - key: availability_zone
                  operator: In
                  values:
                    - local-c
      containers:
        - name: main
          image: sloopstash/mongo-db:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: supervisor-server
              mountPath: /etc/supervisord.conf
              subPath: supervisor-server
            - name: mongo-db-supervisor
              mountPath: /etc/supervisord.d/mongo-db.ini
              subPath: mongo-db-supervisor
            - name: mongo-db-server
              mountPath: /opt/mongo-db/conf/mongod.conf
              subPath: mongo-db-server
            - name: mongo-db-data
              mountPath: /opt/mongo-db/data
            - name: mongo-db-log
              mountPath: /opt/mongo-db/log
          command:
            - "/usr/bin/supervisord"
            - "-c"
            - "/etc/supervisord.conf"
          ports:
            - containerPort: 27017
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 15
            periodSeconds: 20
        - name: log
          image: sloopstash/mongo-db:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: supervisor-server
              mountPath: /etc/supervisord.conf
              subPath: supervisor-server
            - name: mongo-db-log
              mountPath: /opt/mongo-db/log
          command:
            - "/usr/bin/supervisord"
            - "-c"
            - "/etc/supervisord.conf"
      volumes:
        - name: supervisor-server
          configMap:
            name: mongo-db
        - name: mongo-db-supervisor
          configMap:
            name: mongo-db
        - name: mongo-db-server
          configMap:
            name: mongo-db
        - name: mongo-db-data
          persistentVolumeClaim:
            claimName: mongo-db-data
        - name: mongo-db-log
          persistentVolumeClaim:
            claimName: mongo-db-log
  volumeClaimTemplates:
    - metadata:
        name: mongo-db-data
      spec:
        storageClassName: mongo-db-data
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
    - metadata:
        name: mongo-db-log
      spec:
        storageClassName: mongo-db-log
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
